apiVersion: v1
kind: Service
metadata:
  name: federation-apiserver
  namespace: federation
  labels:
    app: federated-cluster
spec:
  selector:
    app: federated-cluster
    module: federation-apiserver
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
